//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherInfo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Weather
    {
        public int Id { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public double Temperature { get; set; }
        public double RelativeHumidity { get; set; }
        public double DewPoint { get; set; }
        public int Pressure { get; set; }
        public string WindDirection { get; set; }
        public Nullable<int> WindVelocity { get; set; }
        public Nullable<int> Claudage { get; set; }
        public Nullable<int> ClaudageLowBound { get; set; }
        public Nullable<int> HorizontallVisibility { get; set; }
        public string WeatherConditions { get; set; }
    }
}
